### ISSUE TITLE
NullPointerException (MapleIL)

### ISSUE THREAD

**Issue by GhastD** [LLVM-but-worse/java-disassembler#70]
`java.lang.NullPointerException
	at java.util.Collections$UnmodifiableCollection.<init>(Unknown Source)
	at java.util.Collections$UnmodifiableSet.<init>(Unknown Source)
	at java.util.Collections.unmodifiableSet(Unknown Source)
	at org.mapleir.stdlib.collections.graph.FastDirectedGraph.getEdges(FastDirectedGraph.java:148)
	at org.mapleir.stdlib.collections.graph.algorithms.ExtendedDfs.dfs(ExtendedDfs.java:104)
	at org.mapleir.stdlib.collections.graph.algorithms.ExtendedDfs.run(ExtendedDfs.java:51)
	at org.mapleir.stdlib.collections.graph.algorithms.SimpleDfs.<init>(SimpleDfs.java:19)
	at org.mapleir.stdlib.collections.graph.algorithms.SimpleDfs.topoorder(SimpleDfs.java:43)
	at org.mapleir.stdlib.collections.graph.algorithms.SimpleDfs.topoorder(SimpleDfs.java:39)
	at org.mapleir.ir.cfg.builder.NaturalisationPass.resolveNaturalHandlerFlow(NaturalisationPass.java:35)
	at org.mapleir.ir.cfg.builder.NaturalisationPass.run(NaturalisationPass.java:29)
	at org.mapleir.ir.cfg.builder.ControlFlowGraphBuilder.buildImpl(ControlFlowGraphBuilder.java:69)
	at org.mapleir.ir.cfg.builder.ControlFlowGraphBuilder.build(ControlFlowGraphBuilder.java:77)
	at org.mapleir.jdaplugin.ILInstructionPrinter.createPrint(ILDecompiler.java:68)
	at club.bytecode.the.jda.decompilers.bytecode.MethodNodeDecompiler.decompile(MethodNodeDecompiler.java:168)
	at club.bytecode.the.jda.decompilers.bytecode.BytecodeDecompiler.decompile(BytecodeDecompiler.java:81)
	at club.bytecode.the.jda.decompilers.bytecode.BytecodeDecompiler.decompileClassNode(BytecodeDecompiler.java:43)
	at club.bytecode.the.jda.gui.fileviewer.DecompileThread.run(DecompileThread.java:46)
`

**Comment by rcx** [comment]
Hi, thanks for letting me know about this. However, I can’t debug this
issue without the binary or jar that caused it. If you are able, could you
please attach? Thanks
